# Generated by Django 4.2.27 on 2025-12-10 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('publicado_en', models.DateField()),
                ('disponible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['titulo'],
            },
        ),
    ]
